build.gradle
src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/controller/SparkUserController.java
src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/dto/SparkUserDTO.java
src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/entity/SparkUser.java
src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/entity/SparkUserRole.java
src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/repository/SparkUserRepository.java
src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/service/SparkUserService.java
src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/service/SparkUserServiceImpl.java
src/main/java/mutsa/yewon/talksparkbe/global/config/WebSecurityConfig.java
src/main/java/mutsa/yewon/talksparkbe/global/exception/CustomTalkSparkException.java
src/main/java/mutsa/yewon/talksparkbe/global/exception/ErrorCode.java
src/main/java/mutsa/yewon/talksparkbe/global/exception/ErrorResponseEntity.java
src/main/java/mutsa/yewon/talksparkbe/global/exception/TalkSparkExceptionHandler.java
src/main/java/mutsa/yewon/talksparkbe/global/security/JWTCheckFilter.java
src/main/java/mutsa/yewon/talksparkbe/global/util/JWTUtil.java
src/test/java/mutsa/yewon/talksparkbe/global/util/JWTUtilTest.java

- closes #4 
회원 인증/인가를 위한 3가지 기능을 구현했습니다.
1. 카카오 API서버와의 통신을 통한 카카오 사용자 정보 추출
- 클라이언트로부터 accessToken 을 받아서 카카오 API서버에 전달 후 로그인/회원가입하고자 하는 유저의 카카오 ID와 닉네임을 추출합니다.
- 카카오ID를 통해서 DB확인 후 사용자가 없으면(회원가입) 생성 후 만들어진 유저 객체를 바탕으로 JWT accessToken 과 refreshToken을 생성하고 유저 정보를 담은 Map클래스에 추가해  반환합니다. 사용자가 있으면 (로그인) 사용자 정보를 가져와  JWT accessToken 과 refreshToken을 생성하여 유저 정보를 담은 Map클래스에 추가해 반환합니다.
2. refreshToken을 받아서 새로운 accessToken을 생성
- 클라이언트로부터 refreshToken을 받아서 유효한 토큰인지 검증한 뒤 유효하면 새로운 accessToken을 생성하여 기존 refreshToken과 함께 반환합니다. 
3. JWTCheckFilter를 도입해 API 이용시 토큰 검증
- Spring Security 의 Filter 중 OncePerRequestFilter 를 상속받아 구현한 필터입니다. 매 API로 들어오는 요청마다 JWT토큰을 검증합니다. 토큰이 없거나 유효하지 않은 토큰에 대해서는 에러 메세지를 JSON형식으로 반환합니다. 
전달사항
@power-minu @lee-youn 이후 개발에 방해가 될듯 하여서 일단은 필터는 만들어만 놓았고 적용시키진 않았습니다! 
현재 시큐리티 설정클래스 보시면 …

Feat/#4 카카오 로그인회원가입 구현

---

build.gradle
src/main/java/mutsa/yewon/talksparkbe/domain/game/config/WebSocketConfig.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomController.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomWebSocketController.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/request/HostCheckRequest.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/view/RoomViewController.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/view/UserViewController.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/repository/RoomParticipateRepository.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/response/RoomListResponse.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/response/RoomParticipantResponse.java
src/main/java/mutsa/yewon/talksparkbe/global/exception/ErrorCode.java
src/main/resources/templates/createRoom.html
src/main/resources/templates/login.html
src/main/resources/templates/roomDetail.html
src/main/resources/templates/roomList.html

- closes #11 
방 시작 전 대기 화면을 위한 기능을 구현했습니다. 방 안에서는 새로고침을 하지 않아도 실시간으로 들어오는 사람들의 목록이 최신화되어 보이도록 했습니다. 이 과정은 STOMP 프로토콜을 사용한 WebSocket 통신으로 구현했습니다.
또한, 방 안에서 방장에게만 시작 버튼이 보이도록 했습니다. 이는 브라우저 로컬스토리지의 액세스 토큰으로 본인이 그 방의 방장인지 알아내는 API를 통해 제공했습니다.
전 과정을 간단한 타임리프 뷰로 작동 확인했습니다.
<details>
<summary>테스트 사진</summary>
</details>
어떤 변경 사항이 있나요?

Feat: #11 방 시작 대기 구현

---

src/main/java/mutsa/yewon/talksparkbe/domain/card/controller/CardController.java
src/main/java/mutsa/yewon/talksparkbe/domain/card/dto/CardCreateDTO.java
src/main/java/mutsa/yewon/talksparkbe/domain/card/dto/CardResponseDTO.java
src/main/java/mutsa/yewon/talksparkbe/domain/card/entity/Card.java
src/main/java/mutsa/yewon/talksparkbe/domain/card/repository/CardRepository.java
src/main/java/mutsa/yewon/talksparkbe/domain/card/service/CardService.java
src/main/java/mutsa/yewon/talksparkbe/domain/card/service/CardServiceImpl.java
src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/dto/SparkUserDTO.java
src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/entity/SparkUser.java
src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/service/SparkUserService.java
src/main/java/mutsa/yewon/talksparkbe/global/config/WebSecurityConfig.java
src/main/java/mutsa/yewon/talksparkbe/global/exception/ErrorCode.java
src/main/java/mutsa/yewon/talksparkbe/global/exception/TalkSparkExceptionHandler.java
src/main/java/mutsa/yewon/talksparkbe/global/security/JWTCheckFilter.java
src/main/java/mutsa/yewon/talksparkbe/global/util/JWTUtil.java

- closes #12 
사용자 명함에 대한 생성, 수정, 조회, 삭제 기능을 구현하였습니다. 명함에 대한 모든 요청은 JWT토큰 인증을 거친 후 처리됩니다. 
1. 생성
사용자는 본인의 정보를 담아서 명함을 생성할 수 있습니다. 이때 필수 항목인 이름, 나이, 전공/직무 는 반드시 채워진 상태에서 요청을 보내야합니다. 형식에 맞지 않는 데이터를 요청으로 받을 시 상태코드 400 과 함께 각 항목에 대한 에러 메세지를 반환합니다.
EX) 
{
"major": "전공/직무는 필수항목입니다.",
"name": "이름은 필수항목입니다."
}
2. 수정
사용자는 자신의 특정 명함을 수정할 수 있습니다. 현재는 명함의 모든 항목을 수정가능하도록 구현하였습니다. 이때도 역시 필수 항목을 채워야만 요청이 성공하도록 구현하였습니다. 또한 본인의 명함만 수정 가능하도록 검증하는 메서드를 추가하였습니다.
3.  조회
사용자는 본인의 모든 명함 또는, 특정 명함을 조회할 수 있습니다.  
4. 삭제
사용자는 본인의 특정 명함을 삭제할 수 있습니다. 이때 본인의 명함만 삭제 가능하도록 검증하는 메서드를 추가하였습니다.
코드 리팩토링 사항
사용자의 카카오ID -> 사용자 엔티티 식별자는 DB에서 자동으로 생성되는 기존 식별자(spark_user_id) 를 사용하도록 리팩토링하였습니다! 이에 따라 사용자 클레임에도 사용자의 식별자를 추가하였습니다.
어떤 변경 사항이 있나요?

Feat/#12 명함 생성/조회/수정/삭제 API 구현

---

build.gradle
src/main/java/mutsa/yewon/talksparkbe/domain/card/CardControllerDocs.java
src/main/java/mutsa/yewon/talksparkbe/domain/card/controller/CardController.java
src/main/java/mutsa/yewon/talksparkbe/domain/card/dto/CardCreateDTO.java
src/main/java/mutsa/yewon/talksparkbe/domain/card/dto/CardResponseDTO.java
src/main/java/mutsa/yewon/talksparkbe/domain/card/service/CardServiceImpl.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomController.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/view/UserViewController.java
src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/SparkUserControllerDocs.java
src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/controller/SparkUserController.java
src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/service/SparkUserServiceImpl.java
src/main/java/mutsa/yewon/talksparkbe/global/config/SwaggerConfig.java
src/main/java/mutsa/yewon/talksparkbe/global/config/WebSecurityConfig.java
src/main/java/mutsa/yewon/talksparkbe/global/exception/ErrorCode.java
src/main/java/mutsa/yewon/talksparkbe/global/exception/TalkSparkExceptionHandler.java
src/main/java/mutsa/yewon/talksparkbe/global/security/JWTCheckFilter.java
src/main/java/mutsa/yewon/talksparkbe/global/swagger/ApiErrorCode.java
src/main/java/mutsa/yewon/talksparkbe/global/swagger/ApiErrorCodes.java
src/main/java/mutsa/yewon/talksparkbe/global/swagger/ErrorResponseDTO.java
src/main/java/mutsa/yewon/talksparkbe/global/swagger/ExampleHolder.java
src/test/java/mutsa/yewon/talksparkbe/domain/card/controller/CardControllerTest.java

- closes #15 
1. Swagger UI 적용을 위한 설정 클래스를 구현하고 API 를 문서화하는 작업을 수행했습니다. (명함, 회원)
2. 기존 Custom ErrorCode 와 Response를 반환하던 저희 API 스펙에 맞게 Swagger UI에도 이를 적용하기 위해서 커스텀 어노테이션을 구현했습니다.  사용 방식은 @ApiErrorCodes()안에 해당하는 ErrorCode만 명시해주시면 됩니다!
3. 명함관련 테스트 코드도 추가해봤습니다.
4. 저는 컨트롤러 부분에 문서화 작업을 진행하면 너무 지저분해져서 그냥 인터페이스 생성 후 컨트롤러가 그를 구현하도록 했습니다. 참고해서 작성하셔도 좋습니다! 
어떤 변경 사항이 있나요?

Feat/#15 swagger UI 적용

---

src/main/java/mutsa/yewon/talksparkbe/TalkSparkBeApplication.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/GuestBookControllerDocs.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/controller/GuestBookController.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/dto/guestBook/GuestBookContent.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/dto/guestBook/GuestBookListDTO.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/dto/guestBook/GuestBookListRequestDTO.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/dto/guestBook/GuestBookListResponse.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/dto/guestBook/GuestBookPostRequestDTO.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/entity/GuestBook.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/entity/GuestBookRoom.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/entity/GuestBookRoomSparkUser.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/repository/GuestBookRoomRepository.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/repository/GuestBookRoomSparkUserRepository.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/service/GuestBookRoomService.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/service/GuestBookService.java
src/main/java/mutsa/yewon/talksparkbe/global/scheduler/Scheduler.java
src/main/java/mutsa/yewon/talksparkbe/global/security/JWTCheckFilter.java
src/main/java/mutsa/yewon/talksparkbe/global/util/JWTUtil.java
src/main/resources/application.yaml

- closes #17 
1. 즐겨찾기 추가
guestBookRoom-sparkUser 사이 중간 데이블에 즐겨찾기 넣는걸로 변경하였습니다. 사용자가 쿼리 파라미터 값으로 넘긴 boolean값으로 해당 즐겨찾기 여부를 업데이트 합니다.
2. spring scheduler 방 데이터 삭제
spring scheduler 로 매일 자정마다 해당 방명록 방을 모든 팀원이 삭제하였으면, 방명록 데이터와 방명록 방 데이터를 모두 삭제합니다. 우선 승범님이 만드신 명함쪽이랑 머지하기 전이여서 방명록 데이터만 고려했습니다. (차후 방데이터와 명함데이터도 넣겠습니다!)
++ @psb3707 @power-minu  매일 자정마다 삭제되는 거 괜찮나요? 데이터가 무조건 바로 삭제되어야하는 게 아니여서 이렇게 설정했는데
혹시 시간을 더 짧게 하는 게 좋을 것 같다고 하시면 해당 코드 비동기로 바꾸겠습니다!
3. 사용자 식별자 코드에 맞게 코드 전체적으로 수정
기존에 kakaoId로 했던 코드들을 사용자 식별자 코드에 맞게 수정하였습니다! 
@psb3707 이부분에서 궁금한 게 있는데 모든 사용자 인증이 필요한 API에서 sparkUserId가 필요로 하는 것 같습니다. 혹시 엄 토큰값에서 사용자 Id를 뽑아오기는 힘든가요?? 프론트가 매번 api요청할 때마다 sparkUserId를 포함해서 보내는 게 약간 부담이 될 것 같아서요! 제가 스프링으로 하는 인증 쪽은 몰라서..
다음 진행 계획
1. 예외 코드와 그에 따른 에러 코드를 추가하고 swagger 코드를 수정할 계획입니다. (-> 전체적인 파일 리펙토링 필요)
2. 명함 …

Feat/#17 방명록 즐겨찾기 데이터 삭제 구현

---

src/main/java/mutsa/yewon/talksparkbe/domain/game/entity/Room.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/GuestBookControllerDocs.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/controller/GuestBookController.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/dto/guestBook/GuestBookContent.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/dto/guestBook/GuestBookListDTO.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/dto/guestBook/GuestBookPostRequestDTO.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/dto/room/GuestBookRoomListDTO.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/dto/room/GuestBookRoomListResponse.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/entity/GuestBookRoom.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/entity/GuestBookRoomSparkUser.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/repository/GuestBookRoomRepository.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/service/GuestBookService.java

- closes #30 
방명록 부분 Swagger UI 적용했습니다.
sparkUserId로 받아오는 부분 getLoggedInUserId()로 수정하였습니다.
어떤 변경 사항이 있나요?
@power-minu 민우님, 방명록 부분에서 카드 테마를 사용해야 하는데, 사용자마다 여러개의 명함을 만들 수 있다보니, 방을 생성할 때 사용자가 어떤 명함으로 참여하는지 데이터가 필요할 것 같습니다!

Refactor/#30 방명록 보관함 swagger 리팩토링

---

src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomController.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/httpResponse/RoomParticipantResponse.java

- closes #32 
게임 내부 관련해 프론트 담당자인 공준혁님과 상의 과정에서, 수정이 필요한 부분들이 발견되어 수정했습니다. 응답 양식에 대한 수정, 추가입니다.
어떤 변경 사항이 있나요?

refactor: #32 프론트 요구사항에 맞춰 리팩토링

---

src/test/java/mutsa/yewon/talksparkbe/domain/card/controller/CardControllerTest.java

CardControllerTest를 주석처리합니다
어떤 변경 사항이 있나요?

Chore: #30 CardControllerTest 주석처리

---

src/test/java/mutsa/yewon/talksparkbe/domain/card/controller/CardControllerTest.java

- closes #이슈
계속 충돌이 해결이 안돼서..
우선 develop의 테스트 부분 release-dev와 동일하게 바꾸려고 합니다!
어떤 변경 사항이 있나요?

Resolve merge conflict

---

src/test/java/mutsa/yewon/talksparkbe/domain/card/controller/CardControllerTest.java

Chore: 주석 변경

---

src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomController.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomSocketIOHandler.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/CardResponseCustomDTO.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/CorrectAnswerDto.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameState.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/QuestionGenerator.java

- closes #43 
게임 관련 추가 수정사항이 있어 작업했습니다.
어떤 변경 사항이 있나요?

refactor: #43 프론트 요구사항 리팩토링

---

src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/CardHolderControllerDocs.java
src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/controller/CardHolderController.java
src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/dto/CardHolderDTO.java
src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/entity/CardHolder.java

- closes #46 
1. 서비스 요구사항에 따라 명함 보관함 속 CardHolder 에 포함된 총 명함 갯수를 저장하고 반환하도록 수정했습니다.
2. 이에 따라 Controller, Service, Swagger 문서, 반환 객체인 CardHolderDTO도 수정했습니다.
어떤 변경 사항이 있나요?

Refactor:#46 명함 보관함 속 명함 보관 객체에 총 명함 갯수 필드 추가

---

src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomController.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/request/RoomCreateRequest.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/entity/QuestionTip.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/httpResponse/RoomListResponse.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/QuestionGenerator.java

질문 안내문구 적용, 방제목검색 정상화

---

src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/controller/CardHolderController.java
src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/dto/MainPageCardHolderDTO.java
src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/service/StoredCardService.java
src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/service/StoredCardServiceImpl.java

- closes #59 
메인 페이지 화면에 보일 사용자가 저장한 명함 목록을 반환하는 API를 추가하였습니다.
어떤 변경 사항이 있나요?

Feat:#59 메인 페이지 화면에 필요한 보관된 명함 목록 반환 API추가

---

src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/service/GuestBookService.java

방명록 내용 리스트를 조회하는 부분에서 각 사용자의 명함 테마 데이터를 추가하였습니다.
익명일 때는 랜덤으로 적용되어 보여집니다.
어떤 변경 사항이 있나요?

Chore: #54 명함 테마 및 익명 명함 테마 추가

---

src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomSocketIOHandler.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/repository/RoomParticipateRepository.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/httpResponse/RoomParticipantResponse.java
src/main/java/mutsa/yewon/talksparkbe/global/exception/ErrorCode.java

방 입장 중복 처리

---

src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomSocketIOHandler.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/repository/RoomParticipateRepository.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/httpResponse/RoomParticipantResponse.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/QuestionGenerator.java
src/main/java/mutsa/yewon/talksparkbe/global/exception/ErrorCode.java

중복입장 오류 배포

---

src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/GameTestController.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
src/main/java/mutsa/yewon/talksparkbe/global/exception/ErrorCode.java
src/main/java/mutsa/yewon/talksparkbe/global/security/JWTCheckFilter.java

방 중복이름 생성 예외처리

---

src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomSocketIOHandler.java

연결 시 메시지 보내기

---

src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomSocketIOHandler.java

연결 끊길때 메시지 보내기

---

src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomSocketIOHandler.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/httpResponse/RoomParticipantResponse.java

오류수정, 로그설정

---

src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomSocketIOHandler.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameState.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/QuestionGenerator.java

문제에서 전공 제외, 빈칸정보 최신화 트래킹

---

src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomSocketIOHandler.java

문제 메시지에서 방제목까지

---

src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomSocketIOHandler.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/request/AnswerSubmitRequest.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/request/GameStartRequest.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/request/QuestionRequest.java

dto들 data로 설정

---

src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomSocketIOHandler.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/CorrectAnswerDto.java

문제 점수판 컬러 적용

---

src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomSocketIOHandler.java
src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/repository/SparkUserRepository.java

트랜잭션 다시 설정

---

src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/entity/SparkUser.java

Chore:#95 회원삭제 버그 수정

---

src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/dto/TeamCardHolderCreateDTO.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomSocketIOHandler.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/CardBlanksDto.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/CorrectAnswerDto.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameState.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/QuestionGenerator.java

- closes #98 
1. 게임 문제 출제 시 중복값, null 값을 모두 제외한 보기 후보들을 만들고 그 안에서 랜덤으로 사용자 수에 따라 선택해 보기들을 만들도록 로직 수정
2. 한 사람의 명함에서 출제된 모든 문제들을 풀고 다음 사람으로 넘어갈 때 확인하는 변수인 currentSubjectId 변경 시점을 통일
3. 불변 객체인 CardBlanksDto 내 필드인 blanks에 값 삭제가 가능하도록 변경
4. 게임이 끝나고 명함 저장 시 TeamCardHolderCreateDTO 의 static 메서드 of를 전달하는 인자가 올바르도록 수정
어떤 변경 사항이 있나요?

Refactor:#98 게임 문제 출제 로직 수정 및 DTO 수정

---

src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/dto/TeamCardHolderCreateDTO.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomSocketIOHandler.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/CardBlanksDto.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/CorrectAnswerDto.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameState.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/QuestionGenerator.java
src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/entity/SparkUser.java

- closes #이슈
1. 게임 문제 출제 시 중복값, null 값을 모두 제외한 보기 후보들을 만들고 그 안에서 랜덤으로 사용자 수에 따라 선택해 보기들을 만들도록 로직 수정
2. 한 사람의 명함에서 출제된 모든 문제들을 풀고 다음 사람으로 넘어갈 때 확인하는 변수인 currentSubjectId 변경 시점을 통일
3. 불변 객체인 CardBlanksDto 내 필드인 blanks에 값 삭제가 가능하도록 변경
4. 게임이 끝나고 명함 저장 시 TeamCardHolderCreateDTO 의 static 메서드 of를 전달하는 인자가 올바르도록 수정
어떤 변경 사항이 있나요?

Refactor/#98 게임 관련 로직 수정

---

src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/CardQuestion.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/UserCardQuestions.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/QuestionGenerator.java
src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/entity/SparkUser.java

- closes #102 
1. 회원 삭제를 위한 엔티티 수정
- 회원 엔티티를 참조하고 있는 엔티티들(RoomParticipate, GuestBookRoomSparkUser) 로 인해 회원 엔티티 삭제가 거부됩니다.
- 이를 해결하기 위해 회원 엔티티의 리스트로 관리되는 위 엔티티들을 Cascade.ALL 옵션으로 같이 삭제되도록 수정하였습니다.
어떤 변경 사항이 있나요?

Refactor:#102 회원 탈퇴 로직 오류 수정을 위한 엔티티 수정

---

src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomSocketIOHandler.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameState.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/QuestionGenerator.java

- closes #106 
현재는 한 문제를 푼 이후에 점수를 공개하기 위해 필요한 데이터를 만드는 과정에서 데이터베이스 접근이 이루어지고 있습니다.
(유저 이름과 명함 테마 데이터를 가져오기 위한 Card 엔티티 접근)
하지만 이미 GameState에서 이 정보를 관리하고 있기에 기존 로직에서 GameState에서 관리하는 cards에서 filter메서드로 데이터를 추출하는 형식으로 리팩토링하여 데이터베이스 접근을 하지않아 성능을 올리도록 수정하였습니다.
어떤 변경 사항이 있나요?

Refactor/#106 점수 기록 로직 리팩토링

---

src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/service/GuestBookService.java

프론트 측에서 테스트 할 때 동시성 이슈로 여러 번 데이터가 생성되는 것으로 추측됩니다..(확실하진 않아서 이후 테스트 상황을 봐야할 것 같습니다..)
현재 주석한 코드는 없어도 로직 상 문제가 없으며, 아마도 데이터 중복 저장을 일으키는 코드로 예상되어 주석처리하였습니다.
어떤 변경 사항이 있나요?

Chore: #54 다중 스레드 동시성 문제 수정

---

.gitignore
src/main/java/mutsa/yewon/talksparkbe/domain/card/dto/CardCreateDTO.java
src/main/java/mutsa/yewon/talksparkbe/domain/card/entity/Card.java
src/main/java/mutsa/yewon/talksparkbe/domain/card/service/CardServiceImpl.java
src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/entity/CardHolder.java
src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/service/StoredCardServiceImpl.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomSocketIOHandler.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/entity/RoomParticipate.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameState.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/entity/GuestBook.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/entity/GuestBookRoomSparkUser.java
src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/entity/SparkUser.java

- closes #111 
회원 엔티티 삭제시 회원 엔티티와 연관관계를 가진(일대다) 모든 엔티티들은 회원 엔티티를 참조하고 있기 때문에 참조 무결성 보장을 위해 회원 엔티티 삭제를 강제로 금지하고 있었습니다. 이를 해결하기 위해서 일대다 관계를 맺고 있는 엔티티들을 생성 시 연관관계를 설정하는 메서드를 만들고 엔티티 생성 마다 이를 설정해주는 방식으로 수정하였습니다.
어떤 변경 사항이 있나요?
- [] 새로운 기능 추가

[Refactor]:#111 회원 삭제 로직 버그 수정을 위한 연관관계 메서드 추가

---

.github/workflows/deploy-main.yml
.gitignore
build.gradle
docker-compose.yml
src/main/java/mutsa/yewon/talksparkbe/domain/game/entity/DummyOption.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameStateService.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameState.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/QuestionGenerator.java
src/main/java/mutsa/yewon/talksparkbe/global/config/SwaggerConfig.java

- closes #112 
1. 게임 참여자들의 퀴즈에 대한 답이 모두 오답일 경우, 서버 측에서 아무런 동작을 하지 않아 프론트 측에서 오류가 발생하는 것을 확인하였습니다.
2. 이를 해결하기 위해 참여자들의 답이 오답일 경우에도, 특정 반환값을 전달하도록 코드를 수정하였습니다.
3. 또한 참여자 수가 4명 미만인 경우, 보기의 최대 수가 참여자 수가 되었던 기존 방식에서 기획분의 요청에 따라 더미 데이터를 활용해 항상 4개의 보기를 전달하도록 수정하였습니다.
어떤 변경 사항이 있나요?

[Chore]:#112 모든 사람이 오답 제출 시에도 응답 값을 반환하도록 수정

---

src/main/java/mutsa/yewon/talksparkbe/domain/game/entity/RoomParticipate.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/RoomState.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/service/GuestBookService.java

1. 방명록 데이터 조회 부분 에러 수정하였습니다!
2. 게임 시작 전(대기)까지 RoomState에 임시로 저장하여 DB접근을 최소화하였으나, 참여자 리스트를 프론트 측에 보내주는 부분에서는SparkUser 엔티티에 대하여 Hibernate 세션이 닫히기 때문에 DB에 접근할 수 밖에 없었습니다..
(RoomState는 SparkUser 자체의 데이터를 모두 저장하는 것이 아니라 필요할 때만 접근하는 것으로 Hibernate 세션이 닫히면 해당 관련 데이터를 가져오지 못함)
3. 게임이 시작할 때 방 참가자 엔티티에 저장하는 것으로 코드를 변경하였으며 방 목록에서도 대기/게임 시작 모두 참가자 수를 알 수 있도록 코드를 변경하였습니다.
++ 그으리고..약간 다른 내용인데 참가자들이 모두 없는 값으로 퀴즈를 낼 때 이상한 것 같습니다.. 
ex) A와 B가 MBTI 내용이 없는데 MBTI내용이 출제될 때
밑에 이미지와 같이 빈 값으로 퀴즈가 출제되며 버튼을 눌렀을 때 넘어가지도 않고 아무런 반응이 없습니다..!
어떤 변경 사항이 있나요?

Refactor/#99 게임 시작 전 후 리팩토링

---

.gitignore
src/main/java/mutsa/yewon/talksparkbe/domain/card/CardControllerDocs.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/GameTestController.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomSocketIOHandler.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/CorrectAnswerDto.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameState.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/QuestionGenerator.java
src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/SparkUserControllerDocs.java
src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/controller/SparkUserController.java
src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/service/RefreshTokenService.java
src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/service/SparkUserServiceImpl.java
src/test/java/mutsa/yewon/talksparkbe/domain/sparkUser/service/RefreshTokenServiceTest.java

- closes #112 
1. 게임 진행 시 사용되는 메서드들을 리팩토링하여 가독성을 향상했습니다.
2. 기존에 가지고 있던 버그들(4인 미만인 경우 보기 수가 4개보다 부족, 모두 틀린 답을 고른 경우 서비스 멈춤 발생)을 해결하고 테스트도 완료했습니다.
어떤 변경 사항이 있나요?

Chore/#112 게임 관련 버그 수정

---

src/main/java/mutsa/yewon/talksparkbe/domain/game/repository/RoomRepository.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/GuestBookControllerDocs.java

Refactor/#130 명함보관함 방명록생성 로직 수정

---

src/main/java/mutsa/yewon/talksparkbe/domain/card/service/CardServiceImpl.java
src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/service/SparkUserService.java
src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/service/SparkUserServiceImpl.java

Fix/#144 명함 저장 로직 오류 수정

---

src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/entity/GuestBookRoomSparkUser.java

방번호 넘겨주는 과정에서 생긴 에러를 해결했습니다.(내림차순 적용 오류)
어떤 변경 사항이 있나요?

Fix: #130 방번호 에러 해결

---

src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/controller/CardHolderController.java
src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/dto/MainPageCardHolderDTO.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/dto/EndGameDto.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/repository/RoomRepository.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameStateManager.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/entity/GuestBookRoom.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/service/GuestBookService.java

Refactor:#149 메인 화면에 필요한 보관된 명함 dto에 명함보관객체 id 추가

---

src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/controller/CardHolderController.java
src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/dto/MainPageCardHolderDTO.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/dto/EndGameDto.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/repository/RoomRepository.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameStateManager.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/entity/GuestBookRoom.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/entity/GuestBookRoomSparkUser.java
src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/service/GuestBookService.java

Merge the develop branch into the main branch.

---

src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/CardHolderControllerDocs.java

Chore:#153 메인 화면에 필요한 보관된 명함 api 문서 데이터 추가

---

src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameQuestionManager.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameStateManager.java
src/main/java/mutsa/yewon/talksparkbe/domain/game/socketiohandler/SocketIoGameHandler.java

1. 같은 문제, 같은 방일 때 동일한 랜덤 질문이 가도록 수정했습니다...!
어떤 변경 사항이 있나요?

Chore: #130 동일한 랜덤 질문 가도록 수정
